<a href="https://colab.research.google.com/github/DeV-Parekh/ML_Tasks/blob/main/Logistic_Regression_SUV_Predictions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression

In [ ]:
import numpy as np 
import pandas as pd 
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
suv_data=pd.read_csv('/content/drive/MyDrive/ML/suv_data.csv')
suv_data.head() 

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
suv_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [ ]:
X = suv_data.iloc[:,[2,3]].values
y = suv_data['Purchased'].values

In [ ]:
suv_data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
gender = pd.get_dummies(suv_data['Gender'], drop_first = True)
gender.head()

Male
0     1
1     1
2     0
3     0
4     1

In [ ]:
# merging 'gender' with 'suv_data'
Data = pd.concat([suv_data , gender ],axis = 1)

In [ ]:
Data.head()

User ID  Gender  Age  EstimatedSalary  Purchased  Male
0  15624510    Male   19            19000          0     1
1  15810944    Male   35            20000          0     1
2  15668575  Female   26            43000          0     0
3  15603246  Female   27            57000          0     0
4  15804002    Male   19            76000          0     1

In [ ]:
X = Data.iloc[:,[2,3,5]].values
y = Data.iloc[:,4].values

In [ ]:
X[:10],y[:10]

(array([[    19,  19000,      1],
        [    35,  20000,      1],
        [    26,  43000,      0],
        [    27,  57000,      0],
        [    19,  76000,      1],
        [    27,  58000,      1],
        [    27,  84000,      0],
        [    32, 150000,      0],
        [    25,  33000,      1],
        [    35,  65000,      0]]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0]))

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler


In [ ]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
# Fitting the Logistic Regression into the Training set

from sklearn.linear_model import LogisticRegression


In [ ]:
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
# Model Eveluation
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.94      0.93        68
           1       0.87      0.84      0.86        32

    accuracy                           0.91       100
   macro avg       0.90      0.89      0.90       100
weighted avg       0.91      0.91      0.91       100



In [ ]:
confusion_matrix(y_test, y_pred)

array([[64,  4],
       [ 5, 27]])

In [ ]:
accuracy_score(y_test,y_pred)

0.91